[package]
name    = "Intergalactica-Discord-Bot-Rust"
version = "0.1.0"
authors = ["Claderoki", "Zengatsu"]
edition = "2018"

[dependencies]
dotenv             = "0.15"
tracing            = "0.1.23"
tracing-subscriber = "0.2"
measurements       = "^0.9.0"
regex              = "1"

[dependencies.tokio]
version  = "1.0"
features = ["macros", "signal", "rt-multi-thread"]

[dependencies.serenity]
features = ["cache", "framework", "standard_framework", "rustls_backend"]

